version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:16
    build:
      context: .
      target: postgresql
      dockerfile: Dockerfile
    volumes:
      - 'volumes/postgresql_data:/bitnami/postgresql/data/'
    ports:
      - '5432:5432'
    environment:
      {# - POSTGRESQL_DATABASE=dev_db #}
      - POSTGRESQL_USERNAME=dev_user
      - POSTGRESQL_PASSWORD=1234
      - POSTGRESQL_POSTGRES_PASSWORD=1234
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dev_user"]
      interval: 10s
      retries: 5
      start_period: 5s
  
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    volumes:
      - "volumes/metabase_data:/metabase_data"
    environment:
    # Configs below is recommended only for development.
    - MB_ENABLE_PASSWORD_LOGIN=false
    - MB_PASSWORD_COMPLEXITY=weak
    - MB_PASSWORD_LENGTH=1

volumes:
  postgresql_data:
    driver: local
  metabase_data:
    driver: local
  
