models:
  - name: dim_time
    description: The 'dim_time' model is a dimension table that contains
      time-related attributes. It includes columns for the specific day, the
      prior and next day, the corresponding day in the prior year, and the day
      of the week in both numerical and textual formats. It also includes
      columns for the day of the month and year, the start and end dates of the
      week, and the corresponding dates for the prior year. The model also
      provides information about the week of the year, the ISO week start and
      end dates, and the corresponding dates and weeks for the prior year.
      Additionally, it includes columns for the month of the year, the month
      name in both full and short formats, the start and end dates of the month,
      and the corresponding dates for the prior year. The model also includes
      columns for the quarter of the year, the start and end dates of the
      quarter, the year number, and the start and end dates of the year. The
      'id' column is a unique identifier for each row, generated by converting
      the 'date_day' column to a string in the 'YYYYMMdd' format and then
      casting it to an integer.
    columns:
      - name: id
        description: This is an integer column that represents the unique identifier for
          each row in the dim_time model. It is derived from the date_day
          column, with the date formatted as 'YYYYMMdd' and then cast to an
          integer.
        data_type: integer
      - name: date_day
        description: This is a date column that represents the specific day for each row
          in the dim_time model. It is used as the base date for calculating
          other date-related columns in the model.
        data_type: date
      - name: prior_date_day
        description: This is a date column that represents the day before the date_day
          for each row in the dim_time model. It is used for comparing data
          between consecutive days.
        data_type: date
      - name: next_date_day
        description: This column represents the date of the following day. It is
          calculated by adding one day to the current date_day value.
        data_type: date
      - name: prior_year_date_day
        description: This column represents the same calendar day in the previous year.
          It is calculated by subtracting one year from the current date_day
          value.
        data_type: date
      - name: prior_year_over_year_date_day
        description: This column represents the same calendar day two years prior. It is
          calculated by subtracting two years from the current date_day value.
        data_type: date
      - name: day_of_week
        description: An integer representing the day of the week, where 1 is Monday and
          7 is Sunday.
        data_type: integer
      - name: day_of_week_name
        description: The full name of the day of the week (e.g., 'Monday', 'Tuesday', etc.).
        data_type: text
      - name: day_of_week_name_short
        description: The abbreviated name of the day of the week (e.g., 'Mon', 'Tue', etc.).
        data_type: text
      - name: day_of_month
        description: This column represents the day of the month for each date in the
          'date_day' column. The values range from 1 to 31, depending on the
          month and year. The data type is double precision.
        data_type: double precision
      - name: day_of_year
        description: This column represents the day of the year for each date in the
          'date_day' column. The values range from 1 to 366, accounting for leap
          years. The data type is double precision.
        data_type: double precision
      - name: week_start_date
        description: This column represents the start date of the week for each date in
          the 'date_day' column. The week start date is determined based on the
          ISO 8601 standard, where Monday is considered the first day of the
          week. The data type is date.
        data_type: date
      - name: week_end_date
        description: The 'week_end_date' column represents the end date of the week for
          the given date in the 'date_day' column. The data type of this column
          is 'date'.
        data_type: date
      - name: prior_year_week_start_date
        description: The 'prior_year_week_start_date' column represents the start date
          of the same week in the prior year for the given date in the
          'date_day' column. The data type of this column is 'date'.
        data_type: date
      - name: prior_year_week_end_date
        description: The 'prior_year_week_end_date' column represents the end date of
          the same week in the prior year for the given date in the 'date_day'
          column. The data type of this column is 'date'.
        data_type: date
      - name: week_of_year
        description: This column represents the week number of the year for the given
          date. It is an integer value ranging from 1 to 53. This value is
          calculated based on the date_day column.
        data_type: integer
      - name: iso_week_start_date
        description: This column represents the start date of the ISO week for the given
          date. The ISO week starts on Monday and ends on Sunday. This value is
          calculated based on the date_day column.
        data_type: date
      - name: iso_week_end_date
        description: This column represents the end date of the ISO week for the given
          date. The ISO week starts on Monday and ends on Sunday. This value is
          calculated based on the date_day column.
        data_type: date
      - name: prior_year_iso_week_start_date
        description: This column represents the start date of the ISO week for the prior
          year. The ISO week starts on Monday and ends on Sunday. The date is in
          the format 'YYYY-MM-DD'.
        data_type: date
      - name: prior_year_iso_week_end_date
        description: This column represents the end date of the ISO week for the prior
          year. The ISO week starts on Monday and ends on Sunday. The date is in
          the format 'YYYY-MM-DD'.
        data_type: date
      - name: iso_week_of_year
        description: This column represents the ISO week number of the year. The ISO
          week starts on Monday and ends on Sunday. The first week of the year
          is the week that contains the first Thursday of the year, according to
          the ISO 8601 standard.
        data_type: integer
      - name: prior_year_week_of_year
        description: This column represents the week number of the prior year. It is an
          integer value that ranges from 1 to 53, depending on the year. This
          value is calculated based on the date_day column.
        data_type: integer
      - name: prior_year_iso_week_of_year
        description: This column represents the ISO week number of the prior year. It is
          an integer value that ranges from 1 to 53, depending on the year. The
          ISO week starts on a Monday and ends on a Sunday, and the first week
          of the year is the one that includes the first Thursday.
        data_type: integer
      - name: month_of_year
        description: This column represents the month number of the year for the given
          date_day. It is an integer value that ranges from 1 (January) to 12
          (December).
        data_type: integer
      - name: month_name
        description: This column represents the full name of the month for the given
          date. The value is a text string, such as 'January', 'February', etc.
        data_type: text
      - name: month_name_short
        description: This column represents the abbreviated name of the month for the
          given date. The value is a text string, such as 'Jan', 'Feb', etc.
        data_type: text
      - name: month_start_date
        description: This column represents the start date of the month for the given
          date. The value is a date in the format 'YYYY-MM-DD'.
        data_type: date
      - name: month_end_date
        description: The 'month_end_date' column represents the last date of the month
          for the given date in the 'date_day' column. It is of 'date' data
          type.
        data_type: date
      - name: prior_year_month_start_date
        description: The 'prior_year_month_start_date' column represents the start date
          of the same month in the prior year for the given date in the
          'date_day' column. It is of 'date' data type.
        data_type: date
      - name: prior_year_month_end_date
        description: The 'prior_year_month_end_date' column represents the end date of
          the same month in the prior year for the given date in the 'date_day'
          column. It is of 'date' data type.
        data_type: date
      - name: quarter_of_year
        description: An integer value representing the quarter of the year for the given
          date. It ranges from 1 to 4, where 1 represents the first quarter
          (January to March), 2 represents the second quarter (April to June), 3
          represents the third quarter (July to September), and 4 represents the
          fourth quarter (October to December).
        data_type: integer
      - name: quarter_start_date
        description: A date value representing the start date of the quarter for the
          given date. For example, if the quarter of the year is 1, the quarter
          start date would be the first day of January of that year.
        data_type: date
      - name: quarter_end_date
        description: A date value representing the end date of the quarter for the given
          date. For example, if the quarter of the year is 1, the quarter end
          date would be the last day of March of that year.
        data_type: date
      - name: year_number
        description: This column represents the year number in the format YYYY. It is an
          integer value.
        data_type: integer
      - name: year_start_date
        description: This column represents the start date of the year. It is a date
          value in the format YYYY-MM-DD.
        data_type: date
      - name: year_end_date
        description: This column represents the end date of the year. It is a date value
          in the format YYYY-MM-DD.
        data_type: date
